Withdraw sm
avakrishn/repo-1123-abc pull request #20
Opened 2019-01-12 20:33 UTC by simonnguyen3054

- Withdraw function worked now. I was able to test it only once. The account that got paid has more ether than before the withdraw. 

- I added calculate payment page instead of putting it in the mint intstwap page. 

- I commented out the hasMatured modifier to make sure it works. 

- I changed the gas to 5000000 and it seems to work better for me. 

- I added conditional statements to grabState function so it renders the appropriate elements. 

- Need to test: Payment Calculation seems to be wrong. Need to double check this together.

2019-01-12 21:37 UTC, mshummer commented on int-swap-dApp/src/js/app.js
> +  return calPaypout;
I don't see where this calPaypout gets used.

2019-01-12 21:39 UTC, mshummer approved these changes
line 128 of app.js returns calPaypout but I don't see where it is then used anywhere?
also app.js line 353-374 was leftover from my previous work and I think can be deleted.  I don't think it is used anywhere.

2019-01-12 22:28 UTC, avakrishn commented on int-swap-dApp/src/js/app.js
> +      debugger
@simonnguyen3054 Can you take out this debugger please.

2019-01-12 22:49 UTC, avakrishn commented on int-swap-dApp/src/js/app.js
> +
@simonnguyen3054 On lines 334-344 the $current_account refers to the first account in ganache and the account that deployed the int-swap contract and will thus not be the proposer or the counterparty, right?

2019-01-12 22:49 UTC, avakrishn commented on int-swap-dApp/src/js/app.js
> +
@simonnguyen3054 Did increasing the gas amount help? Because if it doesn't make a difference we should change it back to 3000000.

2019-01-12 22:49 UTC, avakrishn commented on int-swap-dApp/src/js/app.js
> +      debugger
@simonnguyen3054 Can we remove this debugger as well.

2019-01-12 22:52 UTC, avakrishn requested changes
@simonnguyen3054  I have left some comments that we can go over during our meeting. Also whenever we convert from eth to wei can the calculation be changed to (for example): `window.web3.toWei(eth_amount, "ether");` instead of  `Math.pow(10, 18) * eth_amount`.

2019-01-13 00:16 UTC, avakrishn approved these changes

2019-01-13 00:16 UTC, merged